# Generated by Django 6.0.6 on 2026-06-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order_category_description_alter_food_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='food',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='instructions',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='location',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='food',
            name='whatsapp_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foods/'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
