# Generated by Django 6.0.6 on 2026-06-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_food_category_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='food',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='food',
            name='location',
        ),
        migrations.RemoveField(
            model_name='food',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('rice', 'Rice'), ('chicken', 'Chicken'), ('drinks', 'Drinks'), ('snacks', 'Snacks'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
