# Generated by Django 6.0.6 on 2026-06-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_cart_remove_food_category_remove_food_price_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
